# Generated by Django 5.2.2 on 2025-09-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('interior', 'Interior'), ('urban', 'Urban / Landscape')], max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('describe', models.TextField()),
            ],
        ),
    ]
